### ISSUE TITLE
Doesn't handle negative numbers

### ISSUE THREAD

**Issue by geekskick** [paulboxwell/NumbersToWords#1]
Changing input to -999999 gives error:

```
Traceback (most recent call last):
  File "numberstowords.py", line 83, in <module>
    print("Paul's Mark out of ten: \n\n"+numb_to_text(-999999999999999999999999999999999999,'plain'))
  File "numberstowords.py", line 67, in numb_to_text
    return hundreds(number_str, 0)
  File "numberstowords.py", line 42, in hundreds
    thousands = hundreds(number_str, count + 1)
  File "numberstowords.py", line 42, in hundreds
    thousands = hundreds(number_str, count + 1)
  File "numberstowords.py", line 42, in hundreds
    thousands = hundreds(number_str, count + 1)
  [Previous line repeated 9 more times]
  File "numberstowords.py", line 9, in hundreds
    u= Units[int(number_str[len(number_str)-1])]
ValueError: invalid literal for int() with base 10: '-'
```

**Comment by paulboxwell** [comment]
Latest commit should fix this. Ready for testing.

**Comment by paulboxwell** [comment]
Confirmed fixed.
